---
# tasks file for aem
- name: Create AEM root diretory
  file:
    path: "{{ aem_root_directory }}"
    state: directory
    owner: "{{ aem_user }}"
    mode: 0774
  tags:
    - aem
    - installation
    - aem-installation

- name: Copy the AEM jar file to the remote host
  copy:
    src: "{{ aem_jar_file_full_path }}"
    dest: "{{ aem_root_directory }}/{{ aem_jar_file_full_path | basename }}"
    owner: "{{ aem_user }}"
    mode: 0660
  tags:
    - aem
    - installation
    - aem-installation

- name: Create license.properties file on the remote host
  template:
    src: license.properties.j2
    dest: "{{ aem_root_directory }}/license.properties"
    owner: "{{ aem_user }}"
    mode: 0660
  tags:
    - aem
    - installation
    - aem-installation

- name: Unpack the AEM jar file
  command: "java -jar {{ aem_root_directory }}/{{ aem_jar_file_full_path | basename }} -b {{ aem_root_directory }} -unpack -nofork"
  args:
    creates: "{{ aem_root_directory }}/crx-quickstart/readme.txt"
  tags:
    - aem
    - installation
    - aem-installation

- name: Create the AEM service file
  template:
    src: etc/systemd/system/aem.service.j2
    dest: /etc/systemd/system/aem.service
    owner: root
    mode: 0664
  notify:
    - reread systemd configs
    - restart aem
  tags:
    - aem
    - installation
    - aem-installation

- name: Create /etc/systemd/system/aem.service.d/ directory
  file:
    path: /etc/systemd/system/aem.service.d/
    state: directory
    owner: root
    mode: 0664
  tags:
    - aem
    - installation
    - aem-installation

- name: Create the AEM service configuration file
  template:
    src: etc/systemd/system/aem.service.d/aem.conf.j2
    dest: /etc/systemd/system/aem.service.d/aem.conf
    owner: root
    mode: 0664
  notify:
    - reread systemd configs
    - restart aem
  tags:
    - aem
    - installation
    - aem-installation

- name: Enable end start AEM service
  service:
    name: aem
    state: started
    enabled: yes
  tags:
    - aem
    - installation
    - aem-installation

- name: Wait for AEM to come up
  uri:
    url: "http://127.0.0.1:{{ aem_port }}/libs/granite/core/content/login.html"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 600
  delay: 1
  # when: aem_runmode is search("*author*")
  tags:
    - aem
    - installation
    - aem-installation