---
# defaults file for aem-provision
aem_root_directory: /opt/aem6/
aem_service_user: aem

aem_admin_user: admin
aem_admin_password: admin

aem_transport_user: admin
aem_transport_password: admin
aem_transport_network_interface_name: eth0

aem_license_product_name: ""
aem_license_customer_name: ""
aem_license_product_version: ""
aem_license_downloadID: ""

aem_jar_file_full_path: ""

aem_port: 4502
aem_runmode: author
